name: Release

on:
  schedule:
  - cron: "0 7 * * 2"

jobs:
  publish:
    name: Release all current enqueued dev code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Rebase
        run: |
          git rebase dev
          git push
